// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo.exe -godefs types_windows.go

package serial


func toDWORD(val int) uint32 {
	return uint32(val)
}

func toBYTE(val int) uint8 {
	return uint8(val)
}
